// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0zd1eFekZO7zHZ5VA3xOc6OycXlCkQY',
    appId: '1:764886216810:web:07c36a85d4d2db45635a13',
    messagingSenderId: '764886216810',
    projectId: 'latihan-firebasae',
    authDomain: 'latihan-firebasae.firebaseapp.com',
    storageBucket: 'latihan-firebasae.firebasestorage.app',
    measurementId: 'G-NB66VPMW13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgBncagR_kqx2urlfuCWy7iT3JCTxo3c',
    appId: '1:764886216810:android:352645cb6bd4762b635a13',
    messagingSenderId: '764886216810',
    projectId: 'latihan-firebasae',
    storageBucket: 'latihan-firebasae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUo7HtytkrwjzRYlYiwKxpYH7S7Ap4nMg',
    appId: '1:764886216810:ios:bba79a712b11714c635a13',
    messagingSenderId: '764886216810',
    projectId: 'latihan-firebasae',
    storageBucket: 'latihan-firebasae.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtimeFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUo7HtytkrwjzRYlYiwKxpYH7S7Ap4nMg',
    appId: '1:764886216810:ios:bba79a712b11714c635a13',
    messagingSenderId: '764886216810',
    projectId: 'latihan-firebasae',
    storageBucket: 'latihan-firebasae.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtimeFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN0zd1eFekZO7zHZ5VA3xOc6OycXlCkQY',
    appId: '1:764886216810:web:4097323723376fe8635a13',
    messagingSenderId: '764886216810',
    projectId: 'latihan-firebasae',
    authDomain: 'latihan-firebasae.firebaseapp.com',
    storageBucket: 'latihan-firebasae.firebasestorage.app',
    measurementId: 'G-0PDM9HXJLW',
  );
}
